//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreventivoService
{
    using System;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseContract", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.EventoPreventivoContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.QuoteProdottoContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.InfoBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.BaseCapContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.BaseClienteContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.PreventivoClienteContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.PreventivoFullContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.PreventivoFullInvioEmailContract))]
    public partial class BaseContract : object
    {
        
        private PreventivoService.CANALE CanaleField;
        
        private string CodiceApplicazioneField;
        
        private string CompagniaField;
        
        private PreventivoService.DEVICE DeviceField;
        
        private PreventivoService.SISTEMA_OPERATIVO SistemaOperativoField;
        
        private string VersioneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.CANALE Canale
        {
            get
            {
                return this.CanaleField;
            }
            set
            {
                this.CanaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodiceApplicazione
        {
            get
            {
                return this.CodiceApplicazioneField;
            }
            set
            {
                this.CodiceApplicazioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Compagnia
        {
            get
            {
                return this.CompagniaField;
            }
            set
            {
                this.CompagniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public PreventivoService.DEVICE Device
        {
            get
            {
                return this.DeviceField;
            }
            set
            {
                this.DeviceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.SISTEMA_OPERATIVO SistemaOperativo
        {
            get
            {
                return this.SistemaOperativoField;
            }
            set
            {
                this.SistemaOperativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Versione
        {
            get
            {
                return this.VersioneField;
            }
            set
            {
                this.VersioneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventoPreventivoContract", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class EventoPreventivoContract : PreventivoService.BaseContract
    {
        
        private PreventivoService.Evento EventoField;
        
        private PreventivoService.PolizzaRinnovi PolizzaField;
        
        private PreventivoService.Preventivo PreventivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.Evento Evento
        {
            get
            {
                return this.EventoField;
            }
            set
            {
                this.EventoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.PolizzaRinnovi Polizza
        {
            get
            {
                return this.PolizzaField;
            }
            set
            {
                this.PolizzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.Preventivo Preventivo
        {
            get
            {
                return this.PreventivoField;
            }
            set
            {
                this.PreventivoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuoteProdottoContract", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class QuoteProdottoContract : PreventivoService.BaseContract
    {
        
        private string CodiceProdottoField;
        
        private long IdPuntoVenditaField;
        
        private int MulticanaleField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodiceProdotto
        {
            get
            {
                return this.CodiceProdottoField;
            }
            set
            {
                this.CodiceProdottoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long IdPuntoVendita
        {
            get
            {
                return this.IdPuntoVenditaField;
            }
            set
            {
                this.IdPuntoVenditaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Multicanale
        {
            get
            {
                return this.MulticanaleField;
            }
            set
            {
                this.MulticanaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoBase", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class InfoBase : PreventivoService.BaseContract
    {
        
        private string CodiceProdottoField;
        
        private string StringInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodiceProdotto
        {
            get
            {
                return this.CodiceProdottoField;
            }
            set
            {
                this.CodiceProdottoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StringInfo
        {
            get
            {
                return this.StringInfoField;
            }
            set
            {
                this.StringInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCapContract", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class BaseCapContract : PreventivoService.BaseContract
    {
        
        private string CapField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Cap
        {
            get
            {
                return this.CapField;
            }
            set
            {
                this.CapField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseClienteContract", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.PreventivoClienteContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.PreventivoFullContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.PreventivoFullInvioEmailContract))]
    public partial class BaseClienteContract : PreventivoService.BaseContract
    {
        
        private string CodiceClienteField;
        
        private string CodiceClienteLoggatoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodiceCliente
        {
            get
            {
                return this.CodiceClienteField;
            }
            set
            {
                this.CodiceClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceClienteLoggato
        {
            get
            {
                return this.CodiceClienteLoggatoField;
            }
            set
            {
                this.CodiceClienteLoggatoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreventivoClienteContract", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class PreventivoClienteContract : PreventivoService.BaseClienteContract
    {
        
        private PreventivoService.TIPO_OUTPUT TipoOutputField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public PreventivoService.TIPO_OUTPUT TipoOutput
        {
            get
            {
                return this.TipoOutputField;
            }
            set
            {
                this.TipoOutputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreventivoFullContract", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.PreventivoFullInvioEmailContract))]
    public partial class PreventivoFullContract : PreventivoService.BaseClienteContract
    {
        
        private int AreaEsigenzaField;
        
        private string ClienteCompagniaField;
        
        private string CodicePreventivoField;
        
        private string CodicePropostaField;
        
        private System.DateTime DataCreazioneField;
        
        private string DettaglioField;
        
        private bool FlagModificabileField;
        
        private bool FlagPdfField;
        
        private bool IsResponsiveField;
        
        private string KeyValueParametersField;
        
        private string ListaConvenzioniField;
        
        private string ListaParametriField;
        
        private string NamePdfField;
        
        private string NumeroPreventivoField;
        
        private string PathPdfField;
        
        private float PremioField;
        
        private float PremioAField;
        
        private float PremioDaField;
        
        private string ProdottiField;
        
        private string RinnovoCcuField;
        
        private string RinnovoCodiceAgenziaField;
        
        private string RinnovoCodiceFiscaleField;
        
        private string RinnovoIdPolizzaField;
        
        private string RinnovoKnmnvField;
        
        private string RinnovoNumeroPolizzaField;
        
        private string RinnovoRamoOrdinamentoField;
        
        private string RinnovoSistemaOrigineField;
        
        private string RinnovoTargaField;
        
        private System.DateTime ScadenzaField;
        
        private string TelefonoField;
        
        private int TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AreaEsigenza
        {
            get
            {
                return this.AreaEsigenzaField;
            }
            set
            {
                this.AreaEsigenzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteCompagnia
        {
            get
            {
                return this.ClienteCompagniaField;
            }
            set
            {
                this.ClienteCompagniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodicePreventivo
        {
            get
            {
                return this.CodicePreventivoField;
            }
            set
            {
                this.CodicePreventivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodiceProposta
        {
            get
            {
                return this.CodicePropostaField;
            }
            set
            {
                this.CodicePropostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DataCreazione
        {
            get
            {
                return this.DataCreazioneField;
            }
            set
            {
                this.DataCreazioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Dettaglio
        {
            get
            {
                return this.DettaglioField;
            }
            set
            {
                this.DettaglioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool FlagModificabile
        {
            get
            {
                return this.FlagModificabileField;
            }
            set
            {
                this.FlagModificabileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool FlagPdf
        {
            get
            {
                return this.FlagPdfField;
            }
            set
            {
                this.FlagPdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsResponsive
        {
            get
            {
                return this.IsResponsiveField;
            }
            set
            {
                this.IsResponsiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyValueParameters
        {
            get
            {
                return this.KeyValueParametersField;
            }
            set
            {
                this.KeyValueParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListaConvenzioni
        {
            get
            {
                return this.ListaConvenzioniField;
            }
            set
            {
                this.ListaConvenzioniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListaParametri
        {
            get
            {
                return this.ListaParametriField;
            }
            set
            {
                this.ListaParametriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NamePdf
        {
            get
            {
                return this.NamePdfField;
            }
            set
            {
                this.NamePdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NumeroPreventivo
        {
            get
            {
                return this.NumeroPreventivoField;
            }
            set
            {
                this.NumeroPreventivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PathPdf
        {
            get
            {
                return this.PathPdfField;
            }
            set
            {
                this.PathPdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Premio
        {
            get
            {
                return this.PremioField;
            }
            set
            {
                this.PremioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float PremioA
        {
            get
            {
                return this.PremioAField;
            }
            set
            {
                this.PremioAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float PremioDa
        {
            get
            {
                return this.PremioDaField;
            }
            set
            {
                this.PremioDaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Prodotti
        {
            get
            {
                return this.ProdottiField;
            }
            set
            {
                this.ProdottiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RinnovoCcu
        {
            get
            {
                return this.RinnovoCcuField;
            }
            set
            {
                this.RinnovoCcuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RinnovoCodiceAgenzia
        {
            get
            {
                return this.RinnovoCodiceAgenziaField;
            }
            set
            {
                this.RinnovoCodiceAgenziaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RinnovoCodiceFiscale
        {
            get
            {
                return this.RinnovoCodiceFiscaleField;
            }
            set
            {
                this.RinnovoCodiceFiscaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RinnovoIdPolizza
        {
            get
            {
                return this.RinnovoIdPolizzaField;
            }
            set
            {
                this.RinnovoIdPolizzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RinnovoKnmnv
        {
            get
            {
                return this.RinnovoKnmnvField;
            }
            set
            {
                this.RinnovoKnmnvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RinnovoNumeroPolizza
        {
            get
            {
                return this.RinnovoNumeroPolizzaField;
            }
            set
            {
                this.RinnovoNumeroPolizzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RinnovoRamoOrdinamento
        {
            get
            {
                return this.RinnovoRamoOrdinamentoField;
            }
            set
            {
                this.RinnovoRamoOrdinamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RinnovoSistemaOrigine
        {
            get
            {
                return this.RinnovoSistemaOrigineField;
            }
            set
            {
                this.RinnovoSistemaOrigineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RinnovoTarga
        {
            get
            {
                return this.RinnovoTargaField;
            }
            set
            {
                this.RinnovoTargaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Scadenza
        {
            get
            {
                return this.ScadenzaField;
            }
            set
            {
                this.ScadenzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreventivoFullInvioEmailContract", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class PreventivoFullInvioEmailContract : PreventivoService.PreventivoFullContract
    {
        
        private string ArgomentiDiInteresseField;
        
        private string CapField;
        
        private string CodAgenziaDiRiferimentoField;
        
        private string CodiceAzioneField;
        
        private string CognomeField;
        
        private string ComuneField;
        
        private System.DateTime DataAppuntamentoField;
        
        private string EmailField;
        
        private string FasciaOrariaField;
        
        private string IdFasciaOrariaField;
        
        private string IdsArgomentiDiInteresseField;
        
        private string IndirizzoField;
        
        private string NomeField;
        
        private string NoteField;
        
        private bool TrattamentoDatiPersonaliField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArgomentiDiInteresse
        {
            get
            {
                return this.ArgomentiDiInteresseField;
            }
            set
            {
                this.ArgomentiDiInteresseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cap
        {
            get
            {
                return this.CapField;
            }
            set
            {
                this.CapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodAgenziaDiRiferimento
        {
            get
            {
                return this.CodAgenziaDiRiferimentoField;
            }
            set
            {
                this.CodAgenziaDiRiferimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodiceAzione
        {
            get
            {
                return this.CodiceAzioneField;
            }
            set
            {
                this.CodiceAzioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome
        {
            get
            {
                return this.CognomeField;
            }
            set
            {
                this.CognomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comune
        {
            get
            {
                return this.ComuneField;
            }
            set
            {
                this.ComuneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAppuntamento
        {
            get
            {
                return this.DataAppuntamentoField;
            }
            set
            {
                this.DataAppuntamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FasciaOraria
        {
            get
            {
                return this.FasciaOrariaField;
            }
            set
            {
                this.FasciaOrariaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFasciaOraria
        {
            get
            {
                return this.IdFasciaOrariaField;
            }
            set
            {
                this.IdFasciaOrariaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdsArgomentiDiInteresse
        {
            get
            {
                return this.IdsArgomentiDiInteresseField;
            }
            set
            {
                this.IdsArgomentiDiInteresseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indirizzo
        {
            get
            {
                return this.IndirizzoField;
            }
            set
            {
                this.IndirizzoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool TrattamentoDatiPersonali
        {
            get
            {
                return this.TrattamentoDatiPersonaliField;
            }
            set
            {
                this.TrattamentoDatiPersonaliField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CANALE", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public enum CANALE : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AGGREGATORI = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AGENZIA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PVV = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GERENZE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BROKER = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEB = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVICECENTER = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        B2B2C = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LEGACY = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DEVICE", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public enum DEVICE : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_SET = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOBILE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WEB = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MSITE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TABLET = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SISTEMA_OPERATIVO", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public enum SISTEMA_OPERATIVO : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_SET = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IOS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANDROID = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WIN_PHONE = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evento", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class Evento : object
    {
        
        private string IdEventoField;
        
        private string IdProcessoField;
        
        private string NoteField;
        
        private System.Nullable<System.DateTime> TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEvento
        {
            get
            {
                return this.IdEventoField;
            }
            set
            {
                this.IdEventoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProcesso
        {
            get
            {
                return this.IdProcessoField;
            }
            set
            {
                this.IdProcessoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolizzaRinnovi", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class PolizzaRinnovi : object
    {
        
        private string IdPolizzaField;
        
        private string NumeroPolizzaField;
        
        private string RamoOrdinamentoField;
        
        private string SistemaOrigineField;
        
        private string TargaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPolizza
        {
            get
            {
                return this.IdPolizzaField;
            }
            set
            {
                this.IdPolizzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPolizza
        {
            get
            {
                return this.NumeroPolizzaField;
            }
            set
            {
                this.NumeroPolizzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RamoOrdinamento
        {
            get
            {
                return this.RamoOrdinamentoField;
            }
            set
            {
                this.RamoOrdinamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SistemaOrigine
        {
            get
            {
                return this.SistemaOrigineField;
            }
            set
            {
                this.SistemaOrigineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Targa
        {
            get
            {
                return this.TargaField;
            }
            set
            {
                this.TargaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Preventivo", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class Preventivo : object
    {
        
        private string CcuField;
        
        private string CodiceAgenziaField;
        
        private string CodiceCampagnaField;
        
        private string CodiceFiscaleField;
        
        private string KnmnvField;
        
        private string UtenzaWebField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ccu
        {
            get
            {
                return this.CcuField;
            }
            set
            {
                this.CcuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceAgenzia
        {
            get
            {
                return this.CodiceAgenziaField;
            }
            set
            {
                this.CodiceAgenziaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceCampagna
        {
            get
            {
                return this.CodiceCampagnaField;
            }
            set
            {
                this.CodiceCampagnaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceFiscale
        {
            get
            {
                return this.CodiceFiscaleField;
            }
            set
            {
                this.CodiceFiscaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Knmnv
        {
            get
            {
                return this.KnmnvField;
            }
            set
            {
                this.KnmnvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtenzaWeb
        {
            get
            {
                return this.UtenzaWebField;
            }
            set
            {
                this.UtenzaWebField = value;
            }
        }

        internal static void ToTxt(string text, string v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIPO_OUTPUT", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public enum TIPO_OUTPUT : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FULL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MINIMAL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HISTORY = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DettaglioPreventivo", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.DettaglioPreventivoWeb))]
    public partial class DettaglioPreventivo : object
    {
        
        private int AreaEsigenzaCodiceField;
        
        private string AreaEsigenzaTestoField;
        
        private string CodicePreventivoField;
        
        private System.Nullable<System.DateTime> DataCreazioneField;
        
        private PreventivoService.Etichetta[] EtichetteField;
        
        private string LinkToPdfField;
        
        private string NumeroPreventivoField;
        
        private string PathPdfField;
        
        private string ProdottiField;
        
        private int TipoPreventivoCodiceField;
        
        private string TipoPreventivoTestoField;
        
        private PreventivoService.InfoPremio ValoriPremioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AreaEsigenzaCodice
        {
            get
            {
                return this.AreaEsigenzaCodiceField;
            }
            set
            {
                this.AreaEsigenzaCodiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaEsigenzaTesto
        {
            get
            {
                return this.AreaEsigenzaTestoField;
            }
            set
            {
                this.AreaEsigenzaTestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodicePreventivo
        {
            get
            {
                return this.CodicePreventivoField;
            }
            set
            {
                this.CodicePreventivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCreazione
        {
            get
            {
                return this.DataCreazioneField;
            }
            set
            {
                this.DataCreazioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.Etichetta[] Etichette
        {
            get
            {
                return this.EtichetteField;
            }
            set
            {
                this.EtichetteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkToPdf
        {
            get
            {
                return this.LinkToPdfField;
            }
            set
            {
                this.LinkToPdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPreventivo
        {
            get
            {
                return this.NumeroPreventivoField;
            }
            set
            {
                this.NumeroPreventivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PathPdf
        {
            get
            {
                return this.PathPdfField;
            }
            set
            {
                this.PathPdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prodotti
        {
            get
            {
                return this.ProdottiField;
            }
            set
            {
                this.ProdottiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoPreventivoCodice
        {
            get
            {
                return this.TipoPreventivoCodiceField;
            }
            set
            {
                this.TipoPreventivoCodiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPreventivoTesto
        {
            get
            {
                return this.TipoPreventivoTestoField;
            }
            set
            {
                this.TipoPreventivoTestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.InfoPremio ValoriPremio
        {
            get
            {
                return this.ValoriPremioField;
            }
            set
            {
                this.ValoriPremioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPremio", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts", IsReference=true)]
    public partial class InfoPremio : object
    {
        
        private float PremioField;
        
        private float PremioAField;
        
        private float PremioDaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Premio
        {
            get
            {
                return this.PremioField;
            }
            set
            {
                this.PremioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PremioA
        {
            get
            {
                return this.PremioAField;
            }
            set
            {
                this.PremioAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PremioDa
        {
            get
            {
                return this.PremioDaField;
            }
            set
            {
                this.PremioDaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DettaglioPreventivoWeb", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class DettaglioPreventivoWeb : PreventivoService.DettaglioPreventivo
    {
        
        private bool AreaEsigenzaSpecifiedField;
        
        private string[] CodiciConvenzioneField;
        
        private bool DataCreazioneSpecifiedField;
        
        private bool FlagModificabileField;
        
        private bool FlagModificabileSpecifiedField;
        
        private bool FlagPdfField;
        
        private bool FlagPdfSpecifiedField;
        
        private bool PremioASpecifiedField;
        
        private bool PremioDaSpecifiedField;
        
        private bool PremioSpecifiedField;
        
        private System.Nullable<System.DateTime> ScadenzaField;
        
        private bool ScadenzaSpecifiedField;
        
        private string TipoField;
        
        private bool TipoSpecifiedField;
        
        private string TitoloAreaTestoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AreaEsigenzaSpecified
        {
            get
            {
                return this.AreaEsigenzaSpecifiedField;
            }
            set
            {
                this.AreaEsigenzaSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CodiciConvenzione
        {
            get
            {
                return this.CodiciConvenzioneField;
            }
            set
            {
                this.CodiciConvenzioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DataCreazioneSpecified
        {
            get
            {
                return this.DataCreazioneSpecifiedField;
            }
            set
            {
                this.DataCreazioneSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlagModificabile
        {
            get
            {
                return this.FlagModificabileField;
            }
            set
            {
                this.FlagModificabileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlagModificabileSpecified
        {
            get
            {
                return this.FlagModificabileSpecifiedField;
            }
            set
            {
                this.FlagModificabileSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlagPdf
        {
            get
            {
                return this.FlagPdfField;
            }
            set
            {
                this.FlagPdfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlagPdfSpecified
        {
            get
            {
                return this.FlagPdfSpecifiedField;
            }
            set
            {
                this.FlagPdfSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PremioASpecified
        {
            get
            {
                return this.PremioASpecifiedField;
            }
            set
            {
                this.PremioASpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PremioDaSpecified
        {
            get
            {
                return this.PremioDaSpecifiedField;
            }
            set
            {
                this.PremioDaSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PremioSpecified
        {
            get
            {
                return this.PremioSpecifiedField;
            }
            set
            {
                this.PremioSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Scadenza
        {
            get
            {
                return this.ScadenzaField;
            }
            set
            {
                this.ScadenzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ScadenzaSpecified
        {
            get
            {
                return this.ScadenzaSpecifiedField;
            }
            set
            {
                this.ScadenzaSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TipoSpecified
        {
            get
            {
                return this.TipoSpecifiedField;
            }
            set
            {
                this.TipoSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitoloAreaTesto
        {
            get
            {
                return this.TitoloAreaTestoField;
            }
            set
            {
                this.TitoloAreaTestoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Etichetta", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts", IsReference=true)]
    public partial class Etichetta : object
    {
        
        private string TestoField;
        
        private string ValoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Testo
        {
            get
            {
                return this.TestoField;
            }
            set
            {
                this.TestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valore
        {
            get
            {
                return this.ValoreField;
            }
            set
            {
                this.ValoreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpInfo7", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts.EntitiesOutp" +
        "ut", IsReference=true)]
    public partial class OpInfo7 : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string OutCode1Field;
        
        private string OutCode2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutCode1
        {
            get
            {
                return this.OutCode1Field;
            }
            set
            {
                this.OutCode1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutCode2
        {
            get
            {
                return this.OutCode2Field;
            }
            set
            {
                this.OutCode2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpInfo", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.DettaglioQuoteProdotto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PreventivoService.DettaglioQuoteGaranzie))]
    public partial class OpInfo : object
    {
        
        private string CodErroreField;
        
        private string DescrizioneErroreField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodErrore
        {
            get
            {
                return this.CodErroreField;
            }
            set
            {
                this.CodErroreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescrizioneErrore
        {
            get
            {
                return this.DescrizioneErroreField;
            }
            set
            {
                this.DescrizioneErroreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DettaglioQuoteProdotto", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts", IsReference=true)]
    public partial class DettaglioQuoteProdotto : PreventivoService.OpInfo
    {
        
        private string CodiceProdottoField;
        
        private PreventivoService.FattoreQuotazione[] FattoriField;
        
        private long IdPuntoVenditaField;
        
        private string XmlResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceProdotto
        {
            get
            {
                return this.CodiceProdottoField;
            }
            set
            {
                this.CodiceProdottoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.FattoreQuotazione[] Fattori
        {
            get
            {
                return this.FattoriField;
            }
            set
            {
                this.FattoriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdPuntoVendita
        {
            get
            {
                return this.IdPuntoVenditaField;
            }
            set
            {
                this.IdPuntoVenditaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlResponse
        {
            get
            {
                return this.XmlResponseField;
            }
            set
            {
                this.XmlResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DettaglioQuoteGaranzie", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts", IsReference=true)]
    public partial class DettaglioQuoteGaranzie : PreventivoService.OpInfo
    {
        
        private System.DateTime DataScadenzaPreventivoField;
        
        private PreventivoService.FattoreQuotazione[] FattoriField;
        
        private string ImpostePrezzoTotaleField;
        
        private string ImpostePrezzoWebField;
        
        private PreventivoService.Etichetta[] ListaMessaggiAlertField;
        
        private string PrezzoTotalePropostaField;
        
        private string PrezzoWebPropostaField;
        
        private PreventivoService.SezioneGaranzia[] SezioniGaranzieQuotazioneField;
        
        private string XmlResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataScadenzaPreventivo
        {
            get
            {
                return this.DataScadenzaPreventivoField;
            }
            set
            {
                this.DataScadenzaPreventivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.FattoreQuotazione[] Fattori
        {
            get
            {
                return this.FattoriField;
            }
            set
            {
                this.FattoriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImpostePrezzoTotale
        {
            get
            {
                return this.ImpostePrezzoTotaleField;
            }
            set
            {
                this.ImpostePrezzoTotaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImpostePrezzoWeb
        {
            get
            {
                return this.ImpostePrezzoWebField;
            }
            set
            {
                this.ImpostePrezzoWebField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.Etichetta[] ListaMessaggiAlert
        {
            get
            {
                return this.ListaMessaggiAlertField;
            }
            set
            {
                this.ListaMessaggiAlertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrezzoTotaleProposta
        {
            get
            {
                return this.PrezzoTotalePropostaField;
            }
            set
            {
                this.PrezzoTotalePropostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrezzoWebProposta
        {
            get
            {
                return this.PrezzoWebPropostaField;
            }
            set
            {
                this.PrezzoWebPropostaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.SezioneGaranzia[] SezioniGaranzieQuotazione
        {
            get
            {
                return this.SezioniGaranzieQuotazioneField;
            }
            set
            {
                this.SezioniGaranzieQuotazioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlResponse
        {
            get
            {
                return this.XmlResponseField;
            }
            set
            {
                this.XmlResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FattoreQuotazione", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class FattoreQuotazione : object
    {
        
        private string FattoreCodiceField;
        
        private string FattoreDescrizioneField;
        
        private bool FattoreModificabileField;
        
        private int FattoreOrdineField;
        
        private string FattoreValoreDefaultField;
        
        private PreventivoService.OggettoFattoreValore[] FattoreValoriField;
        
        private bool FattoreVisibileInQuotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FattoreCodice
        {
            get
            {
                return this.FattoreCodiceField;
            }
            set
            {
                this.FattoreCodiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FattoreDescrizione
        {
            get
            {
                return this.FattoreDescrizioneField;
            }
            set
            {
                this.FattoreDescrizioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FattoreModificabile
        {
            get
            {
                return this.FattoreModificabileField;
            }
            set
            {
                this.FattoreModificabileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FattoreOrdine
        {
            get
            {
                return this.FattoreOrdineField;
            }
            set
            {
                this.FattoreOrdineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FattoreValoreDefault
        {
            get
            {
                return this.FattoreValoreDefaultField;
            }
            set
            {
                this.FattoreValoreDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.OggettoFattoreValore[] FattoreValori
        {
            get
            {
                return this.FattoreValoriField;
            }
            set
            {
                this.FattoreValoriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FattoreVisibileInQuota
        {
            get
            {
                return this.FattoreVisibileInQuotaField;
            }
            set
            {
                this.FattoreVisibileInQuotaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OggettoFattoreValore", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class OggettoFattoreValore : object
    {
        
        private string CodiceValoreField;
        
        private string DescrizioneValoreField;
        
        private int OrdineValoreField;
        
        private string ValoreField;
        
        private bool VisibileInQuotazioneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceValore
        {
            get
            {
                return this.CodiceValoreField;
            }
            set
            {
                this.CodiceValoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescrizioneValore
        {
            get
            {
                return this.DescrizioneValoreField;
            }
            set
            {
                this.DescrizioneValoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdineValore
        {
            get
            {
                return this.OrdineValoreField;
            }
            set
            {
                this.OrdineValoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valore
        {
            get
            {
                return this.ValoreField;
            }
            set
            {
                this.ValoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VisibileInQuotazione
        {
            get
            {
                return this.VisibileInQuotazioneField;
            }
            set
            {
                this.VisibileInQuotazioneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SezioneGaranzia", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class SezioneGaranzia : object
    {
        
        private string CodiceSezioneField;
        
        private string DescrizioneEstesaSezioneField;
        
        private string DescrizioneSezioneField;
        
        private PreventivoService.OggettoGaranzia[] OpzioniGaranzieField;
        
        private int OrdineSezioneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceSezione
        {
            get
            {
                return this.CodiceSezioneField;
            }
            set
            {
                this.CodiceSezioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescrizioneEstesaSezione
        {
            get
            {
                return this.DescrizioneEstesaSezioneField;
            }
            set
            {
                this.DescrizioneEstesaSezioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescrizioneSezione
        {
            get
            {
                return this.DescrizioneSezioneField;
            }
            set
            {
                this.DescrizioneSezioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.OggettoGaranzia[] OpzioniGaranzie
        {
            get
            {
                return this.OpzioniGaranzieField;
            }
            set
            {
                this.OpzioniGaranzieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdineSezione
        {
            get
            {
                return this.OrdineSezioneField;
            }
            set
            {
                this.OrdineSezioneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OggettoGaranzia", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class OggettoGaranzia : object
    {
        
        private string CodiceSezioneGaranziaField;
        
        private string CodiceTestoSHPField;
        
        private string DescrizioneGaranziaField;
        
        private PreventivoService.FattoreQuotazione[] FattoriDiGaranziaField;
        
        private bool GaranziaAbilitataField;
        
        private bool GaranziaSelezionataField;
        
        private bool GaranziaVisibileField;
        
        private int OrdineGaranziaField;
        
        private string PremioAnnualeLordoField;
        
        private string PremioAnnualeNettoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceSezioneGaranzia
        {
            get
            {
                return this.CodiceSezioneGaranziaField;
            }
            set
            {
                this.CodiceSezioneGaranziaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceTestoSHP
        {
            get
            {
                return this.CodiceTestoSHPField;
            }
            set
            {
                this.CodiceTestoSHPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescrizioneGaranzia
        {
            get
            {
                return this.DescrizioneGaranziaField;
            }
            set
            {
                this.DescrizioneGaranziaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PreventivoService.FattoreQuotazione[] FattoriDiGaranzia
        {
            get
            {
                return this.FattoriDiGaranziaField;
            }
            set
            {
                this.FattoriDiGaranziaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GaranziaAbilitata
        {
            get
            {
                return this.GaranziaAbilitataField;
            }
            set
            {
                this.GaranziaAbilitataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GaranziaSelezionata
        {
            get
            {
                return this.GaranziaSelezionataField;
            }
            set
            {
                this.GaranziaSelezionataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GaranziaVisibile
        {
            get
            {
                return this.GaranziaVisibileField;
            }
            set
            {
                this.GaranziaVisibileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdineGaranzia
        {
            get
            {
                return this.OrdineGaranziaField;
            }
            set
            {
                this.OrdineGaranziaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PremioAnnualeLordo
        {
            get
            {
                return this.PremioAnnualeLordoField;
            }
            set
            {
                this.PremioAnnualeLordoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PremioAnnualeNetto
        {
            get
            {
                return this.PremioAnnualeNettoField;
            }
            set
            {
                this.PremioAnnualeNettoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoComune", Namespace="http://schemas.datacontract.org/2004/07/it.RMA.CompanySite.Contracts")]
    public partial class InfoComune : object
    {
        
        private string CapField;
        
        private string CodiceIstatComuneField;
        
        private string CodiceProvinciaField;
        
        private string DescrizioneComuneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cap
        {
            get
            {
                return this.CapField;
            }
            set
            {
                this.CapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceIstatComune
        {
            get
            {
                return this.CodiceIstatComuneField;
            }
            set
            {
                this.CodiceIstatComuneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceProvincia
        {
            get
            {
                return this.CodiceProvinciaField;
            }
            set
            {
                this.CodiceProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescrizioneComune
        {
            get
            {
                return this.DescrizioneComuneField;
            }
            set
            {
                this.DescrizioneComuneField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PreventivoService.IPreventivatoriService")]
    public interface IPreventivatoriService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreventivatoriService/SalvaPreventivoAreaRiservata", ReplyAction="http://tempuri.org/IPreventivatoriService/SalvaPreventivoAreaRiservataResponse")]
        System.Threading.Tasks.Task<PreventivoService.DettaglioPreventivo> SalvaPreventivoAreaRiservataAsync(PreventivoService.PreventivoFullContract datiPreventivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreventivatoriService/InvioPreventivoByEmail", ReplyAction="http://tempuri.org/IPreventivatoriService/InvioPreventivoByEmailResponse")]
        System.Threading.Tasks.Task<string> InvioPreventivoByEmailAsync(PreventivoService.PreventivoFullInvioEmailContract datiPreventivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreventivatoriService/DownloadPreventivo", ReplyAction="http://tempuri.org/IPreventivatoriService/DownloadPreventivoResponse")]
        System.Threading.Tasks.Task<string> DownloadPreventivoAsync(PreventivoService.PreventivoFullContract datiPreventivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreventivatoriService/GetPreventiviByCodiceCliente", ReplyAction="http://tempuri.org/IPreventivatoriService/GetPreventiviByCodiceClienteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Array))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.OpInfo7))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.DettaglioPreventivoWeb))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.DettaglioPreventivo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.Etichetta[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.Etichetta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.InfoPremio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.DettaglioPreventivoWeb[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.OpInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.DettaglioPreventivo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.PreventivoFullContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.BaseClienteContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.BaseContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.CANALE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.DEVICE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.SISTEMA_OPERATIVO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.PreventivoFullInvioEmailContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.PreventivoClienteContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.TIPO_OUTPUT))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.EventoPreventivoContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.Evento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.PolizzaRinnovi))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.Preventivo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.QuoteProdottoContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.DettaglioQuoteProdotto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.FattoreQuotazione[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.FattoreQuotazione))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.OggettoFattoreValore[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.OggettoFattoreValore))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.InfoBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.DettaglioQuoteGaranzie))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.SezioneGaranzia[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.SezioneGaranzia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.OggettoGaranzia[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.OggettoGaranzia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.BaseCapContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.InfoComune[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PreventivoService.InfoComune))]
        System.Threading.Tasks.Task<System.Array> GetPreventiviByCodiceClienteAsync(PreventivoService.PreventivoClienteContract datiPreventivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreventivatoriService/GestioneEventoPreventivo", ReplyAction="http://tempuri.org/IPreventivatoriService/GestioneEventoPreventivoResponse")]
        System.Threading.Tasks.Task<PreventivoService.OpInfo> GestioneEventoPreventivoAsync(PreventivoService.EventoPreventivoContract param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreventivatoriService/GetSHPQuote", ReplyAction="http://tempuri.org/IPreventivatoriService/GetSHPQuoteResponse")]
        System.Threading.Tasks.Task<PreventivoService.DettaglioQuoteProdotto> GetSHPQuoteAsync(PreventivoService.QuoteProdottoContract datiPreventivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreventivatoriService/PricingSHPQuote", ReplyAction="http://tempuri.org/IPreventivatoriService/PricingSHPQuoteResponse")]
        System.Threading.Tasks.Task<PreventivoService.DettaglioQuoteGaranzie> PricingSHPQuoteAsync(PreventivoService.InfoBase infoPreventivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreventivatoriService/SaveSHPQuote", ReplyAction="http://tempuri.org/IPreventivatoriService/SaveSHPQuoteResponse")]
        System.Threading.Tasks.Task<PreventivoService.OpInfo7> SaveSHPQuoteAsync(PreventivoService.InfoBase infoPreventivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreventivatoriService/GetComuniProvinciaByCap", ReplyAction="http://tempuri.org/IPreventivatoriService/GetComuniProvinciaByCapResponse")]
        System.Threading.Tasks.Task<PreventivoService.InfoComune[]> GetComuniProvinciaByCapAsync(PreventivoService.BaseCapContract infoPreventivo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IPreventivatoriServiceChannel : PreventivoService.IPreventivatoriService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class PreventivatoriServiceClient : System.ServiceModel.ClientBase<PreventivoService.IPreventivatoriService>, PreventivoService.IPreventivatoriService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PreventivatoriServiceClient() : 
                base(PreventivatoriServiceClient.GetDefaultBinding(), PreventivatoriServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPreventivatoriService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreventivatoriServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PreventivatoriServiceClient.GetBindingForEndpoint(endpointConfiguration), PreventivatoriServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreventivatoriServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PreventivatoriServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreventivatoriServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PreventivatoriServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PreventivatoriServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PreventivoService.DettaglioPreventivo> SalvaPreventivoAreaRiservataAsync(PreventivoService.PreventivoFullContract datiPreventivo)
        {
            return base.Channel.SalvaPreventivoAreaRiservataAsync(datiPreventivo);
        }
        
        public System.Threading.Tasks.Task<string> InvioPreventivoByEmailAsync(PreventivoService.PreventivoFullInvioEmailContract datiPreventivo)
        {
            return base.Channel.InvioPreventivoByEmailAsync(datiPreventivo);
        }
        
        public System.Threading.Tasks.Task<string> DownloadPreventivoAsync(PreventivoService.PreventivoFullContract datiPreventivo)
        {
            return base.Channel.DownloadPreventivoAsync(datiPreventivo);
        }
        
        public System.Threading.Tasks.Task<System.Array> GetPreventiviByCodiceClienteAsync(PreventivoService.PreventivoClienteContract datiPreventivo)
        {
            return base.Channel.GetPreventiviByCodiceClienteAsync(datiPreventivo);
        }
        
        public System.Threading.Tasks.Task<PreventivoService.OpInfo> GestioneEventoPreventivoAsync(PreventivoService.EventoPreventivoContract param)
        {
            return base.Channel.GestioneEventoPreventivoAsync(param);
        }
        
        public System.Threading.Tasks.Task<PreventivoService.DettaglioQuoteProdotto> GetSHPQuoteAsync(PreventivoService.QuoteProdottoContract datiPreventivo)
        {
            return base.Channel.GetSHPQuoteAsync(datiPreventivo);
        }
        
        public System.Threading.Tasks.Task<PreventivoService.DettaglioQuoteGaranzie> PricingSHPQuoteAsync(PreventivoService.InfoBase infoPreventivo)
        {
            return base.Channel.PricingSHPQuoteAsync(infoPreventivo);
        }
        
        public System.Threading.Tasks.Task<PreventivoService.OpInfo7> SaveSHPQuoteAsync(PreventivoService.InfoBase infoPreventivo)
        {
            return base.Channel.SaveSHPQuoteAsync(infoPreventivo);
        }
        
        public System.Threading.Tasks.Task<PreventivoService.InfoComune[]> GetComuniProvinciaByCapAsync(PreventivoService.BaseCapContract infoPreventivo)
        {
            return base.Channel.GetComuniProvinciaByCapAsync(infoPreventivo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPreventivatoriService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPreventivatoriService))
            {
                return new System.ServiceModel.EndpointAddress("http://ftc001soa.rmag.local:8085/PreventivatoriService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PreventivatoriServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPreventivatoriService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PreventivatoriServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPreventivatoriService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPreventivatoriService,
        }
    }
}
